name = "bunup_plugin_gleam_demo"
version = "1.0.0"
target = "javascript"

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
